name: Mirror to GitLab
on:
  push:
    branches:
      - main
jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Push to GitLab
        env:
          GITLAB_TOKEN: ${{ secrets.GITLABTOKEN }}
        run: |
          git config --global user.name "Doron Gut"
          git config --global user.email "dorong@eprsys.co.il"
          git remote add gitlab https://oauth2:${GITLAB_TOKEN}@gitlab.com/epr-gvia/reportgenerator.core.git
          git fetch --all
          git push gitlab 'refs/heads/*:refs/heads/*' 'refs/tags/*:refs/tags/*'